# -*- coding: utf-8 -*-
"""Coding problem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KeJdYqK4_Uhp3ZOhfEQLH2D2Ry7bhnfH
"""

str1 = input()
lower_str1 = str1.lower()
vowel_count = 0
vowels = "aeiou"
for char in lower_str1:
  if char in vowels:
    vowel_count += 1
print(lower_str1)
print(vowel_count)

str1=input()
lower_srt=str1.lower()
count=0
for i in lower_srt:
  if i=='a' or i=='e' or i=='i' or i=='o' or i=='u':
    count+=1
print(lower_srt)
print(count)

bill=int(input())
if bill <= 100:
  total=(bill*3)
  print(total)
elif bill>100 and bill<150:
  total=(bill*4)
  print(total)
elif bill>150 and bill<200:
  total=(bill*5)
  print(total)
elif bill>200:
  total=(bill*10)
  print(total)

units=int(input())
if units<=100:
  total=(units*3)
  print(total)
elif units>100 and units<150:
  total=((100*3)+((units-100)*4))
  print(total)
elif units>150 and units<200:
  total=((100*3)+(50*4)+((units-150)*5))
  print(total)
elif units>200:
  total=((100*3)+(50*4)+(50*5)+((units-200)*10))
  print(total)

val=int(input())
val2=int (input())
sum=0
for i in range(val,val2):
  sum+=i
print(sum)

val=int(input())
val2=int (input())
for i in range(val,val2):
  print(i)

n=int(input())
sum=1
for i in range(n):
  m=int(input())
  sum*=m
print(sum)

n = int (input())
m = int(input())
for i in range(n,m):
    if i%2 ==0:
      print('+ '*m)
    else:
      print('- '*m)

m=int(input())
n=int(input())
for i in range(1,m+1):
  if i==1 or i==m+2:
    print("+"+"-"*((n+2)-2)+"+")
  else:
    print("|"+" "*((n+2)-2)+"|")
print("+"+"-"*((n+2)-2)+"+")

n=int(input())
count=0
if n==0 or n==1:
  print("Enter greater then one")
elif n>1:
  for i in range (2,n):
    if (n%i)==0:
      count+=1
      break
  if count==0:
    print("Prime")
  else:
    print("Not Prime")

n=int(input())
for i in range(2,n+1):
  if n>1:
    fact=0
  else:
    fact=1
  for j in range (2,i):
    if (i%j)==0:
      fact+=1
  if fact==0:
    print(i)
  else:
    pass

list=int(input())
max=0
for i in range( list):
    m=int(input())
    if m<max:
        max=max
    else:
        max=m
print(max)

n=int(input())
original=n
reverse=0

while n>0:
 digit= n%10
 reverse=reverse*10+digit
 n=n//10
print(reverse)
if original==reverse:
 print("yes")
else:
 print("No")

n=int(input())
factor=set()
sum=0
for i in range(1,n):
  if n%i==0:
    factor.add(i)
    sum+=i
print(factor)
print(sum)

list1=[2,3,4,5]
max=0
for i in range(len(list1)):
    for j in range(i+1,len(list1)):
        if list1[i]*list1[j]>max:
            max=list1[i]*list1[j]
print(max)

list1=[2,3,4,5,6]
max=0
s_max=0
for i in list1:
  if i>max:
    s_max=max
    max=i
  elif(s_max<i and i!=max):
    s_max=i
print(s_max)

x = int(input())        #schools
y = int(input())        #students
z=int(input())          #passed_students
passing_percent=x*y/2
if z>passing_percent:
  print("yes")
else:
  print("no")

x=int(input()) #bill
y=int(input()) #coin
total=x*y//100
if (x*y<100):
    print(1)
else:
    print(total)

for i in range(1,11):
    for j in range(1,11):
        print(str(i)+"*"+str(j)+"=",i*j)
print("\n")

n=5
for i in range(1,n+1):
    for j in range(i,0,-1):
        print(j,end=" ")
    print()

n = int(input())
for i in range(1,n+1):
    var = " "
    var1 = " "
    ch = n-i
    for j in range(1,i+1):
        # var = str(j)+var
        var1 += str(j)+" "
        var = str(j)+var
    print(var1+(ch*" ")+(ch*" ")+(ch*" ")+var)

n=int(input())
for i in range(1,n+1):
  string_normal=""
  string_reverse=""
  spaces = n-i
  for j in range(1,i+1):
    string_normal+=str(j)+" "
    end_reverse=((spaces*" ")+string_reverse)
    start_string=(string_normal+spaces*" ")
  print(spaces*" ")+string_normal+(spaces*" ")+(spaces*" ")+string_reverse

list1 = list(map(int, input().split()))
max=0
min=
for i in list1:
  if i > max :
    max=i
  if i<min:
    min=i
print(max)
print(min)

x=int(input())
if x<=100:
    print("No Discount")
elif 100<x and x<=1000:
    print(x-25)
elif 1000<x and x<=5000:
    print(x-100)
else:
    print(x-500)

list1=[1,2,34,5,7,4,8,9,12]
target=int(input())
list1=sorted(list1)
print(list1)
for i in range(len(list1)):
  if list1[i]==target:
    print(i)
    break
  elif list1[i]>target:
    print(i)
    break

list1=[1,2,34,5,7,4,8,9,12]
target=int(input())
count=0
pos=0
for i in range(len(list1)):
  if list1[i]==target:
    print(i)
    break
if list1[i]>target:
   print(i)
   count+=1