# -*- coding: utf-8 -*-
"""Day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VlStgsNwkT6joTyPfoZTHTXdmoJC4Qt
"""

str1 = input('entert 1st string')
str2 = input('enter 2nd string')
if str1[-3:]==str2[-3:]:
  print('equal')
else:
  print('not equal')

str1 = input('entert 1st string')
str2 = input('enter 2nd string')
if str1[:3]==str2[:3]:
  print('equal')
else:
  print('not equal')

list1=[1,6,4,9,3]
print(sorted(list1))

tup1=(3,4 ,8 ,1)
print(1 in tup1)
print(3 not in tup1)

n= int (input())
for i in range(1,n+1):
  print(str(i)*i)

def function_1( arg1,arg2):
  if arg1<arg2:
    print (arg1+arg2)
  else:
    print(arg1-arg2)
a=int (input ('enter a'))
b=int(input('enter b'))
function_1(a,b)

def factorial(n):
  fact=1
  for i in range(1,n+1):
    fact*=i
  print(fact)
n=int (input(' enter n value'))

factorial(n)

n = int(input())
list1=[]
for i in range(1,n+1):
  a=i**2
  list1.append(a)
print(list1)