# -*- coding: utf-8 -*-
"""Day2 scaler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pe4N9wMrPrSqO_Q804c2O7MOstpGsrR7
"""

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset("iris")

sns.pairplot(df)
plt.show()

sns.pairplot(df, hue="species")

import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset("iris")

corr = df.corr(numeric_only=True)

sns.heatmap(corr,annot=True,cmap="YlGnBu")
plt.title( "Correlation heatmap")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset("iris")

sns.countplot(x="species",data=df)
plt.title("Count of Each Species")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset("iris")

sns.boxplot(x="species",y="petal_length",data=df)
plt.title("Count of Each Species")
plt.show()