# -*- coding: utf-8 -*-
"""Day2_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFXg7NrJ0V4p5PHQKup4dUpaz6092Ecv
"""

pip install pandas

import pandas as pd                           #series
a = [1,True,'megha']
var1 = pd.Series(a)
print(var1)
print(var1[1])
var1 = pd.Series(a,index=[1,2,3])
print(var1)
print(var1[2])

data = {                                                #dataframes
    'Name':['vasu','anu','nikhi'],
    'age':[20,25,28],
    'score':[90,80,70]
}
var2 = pd.DataFrame(data)
print(var2)

print('Name')
print(var2.loc[1])
print(var2.loc[[1]])
print(0,'Name')

print(var2.loc[[1,2]])

series_list = [1,2,3,4,5,6]
df = pd.DataFrame(series_list,index = ['x','y','z','a','b','c'])
print(df)
print(df.loc['y'])

import pandas as pd
df = pd.read_csv('customers-100.csv')
df.head()

import pandas as pd
df = pd.read_csv('people_data.csv',usecols=["First Name","Job Title"],nrows=3)
df.head()

import pandas as pd
df = pd.read_csv('people_data.csv',usecols=["First Name","Job Title","Sex"],skiprows=[2,3])
df.head()

import pandas as pd
df = pd.read_excel('Weather_data.xlsx')
df.head()

a = df.groupby("Job Title")
a.get_group("Games developer")

filtered_df = df.loc[df['Sex'] == "Male", ['First Name','Job Title']]
print(filtered_df)

filtered_df = df.loc[df['Job Title'] == "Games developer", ['First Name','Job Title']]
print(filtered_df)

filtered_df = df.query('Sex == "Male" and `Job Title`=="Games developer"')
print(filtered_df)