# -*- coding: utf-8 -*-
"""Day2 Matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8-CTlqm-59C8aZL7fB4WAYRsZL8upsZ
"""

import matplotlib.pyplot as plt
import pandas as pd

x = [1,2,3]
y = [4,5,2]

plt.plot(x,y)
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

data = {
    "salary":[25000,30000,37000,2800,39000,4800,55000]
}
df = pd.DataFrame(data)
print(df.head())
df.shape

plt.plot(df["salary"])
plt.grid()
plt.show()

plt.plot(df["salary"],color="red",marker="o",linestyle=":",linewidth=5)
plt.grid()
plt.show()

plt.hist(df["salary"],bins=8)
plt.show()

df["dept"] = ["HR" , "FINANCE", "CS","IT","MANAGEMENT","SALES","MARKETING"]
df.head()

count = df["dept"].value_counts()
print(count)

plt.pie(count,labels=count.index,autopct="%1.6f",explode=[0,0,0,0,0,0,0])
plt.show()

df["age"] = [22,24,25,21,19,30,34]
df.head()

plt.bar(df["age"],df["salary"],color="blue",width=0.5)
plt.show()