# -*- coding: utf-8 -*-
"""Day2 numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRpTh0bPfwVln9c8ENrG5dpUOSqnsJXb
"""

pip install numpy

import numpy as np
arr1 =np.array([1,2,3,4,5])
print(arr1)
print(arr1[3:])

arr2=np.array([[1,2],[2,3]])
print(arr2)
print(arr2[0][0])
print(arr2[0][1])
print(arr2[1][0])
print(arr2[1][1])

for i in range(len(arr2)):
  for j in range(len(arr2[i])):
    print(i,j)

for i in range(len(arr2)):
  for j in range(len(arr2[i])):
    print(i**j)

arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,5,3]]])
print(arr3)
x=arr3[0][0][0]       #arr[block][row][col]
x1=arr3[0][0][1]
x2=arr3[0][0][2]
print(x)
print(x1)
print(x2)

print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.ndim)

print('zeros:',np.zeros((3,3)))
print('ones:',np.ones((2,2)))
print('identity:',np.eye(3))
print('arrange:',np.arange(0,10,3))         #(start,end,step)
print('linespace:',np.linspace(1,5,10))     #(start ,end ,range)

a=np.array([1,2,3])
b=np.array([4,5,6])
print('Add',a+b)
print('subtract',a-b)
print('multiply',a*b)
print('div',a/b)
print(np.dot(a,b))

list1 = [10,20,30,40]
list2 = [1,2,3,4]

arr_list1 = np.array(list1)
arr_list2 = np.array(list2)
print('Add',arr_list1+arr_list2)
print('subtract',arr_list1-arr_list2)
print('multiply',arr_list1*arr_list2)
print('div',arr_list1/arr_list2)
print(np.dot(arr_list1,arr_list2))

arr = np.array([10,20,30,40])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))

a= np.random.rand(3,5)
print(a)
b=np.random.randint(1,100,(3,3))
print(b)